### ISSUE TITLE
How to generate RSA messages

### ISSUE THREAD

**Issue by jlgordo** [kula99/applepay-rsa-crypto-demo#1]
Hi!, i'm developing apple pay integration and we have just finished with ECDSA way, but I can't make my iphone generates a RSA query to validate our code against a real sample. I have read that it depends on the country where the payment is processed, but I have tried with all of [this list](http://www.apple.com/ios/feature-availability/#apple-pay) and all my payment requests returns me ECv1 messages.

Can you help me to generate a RSAv1 message, please?

Thanks!

**Comment by jlgordo** [comment]
@kula99, please, are you there?
Thanks!

**Comment by jlgordo** [comment]
Sorry, @kula99, I didn't wanted to clise this issue,

**Comment by kula99** [comment]
Sorry I was on my vacation these days... 
And sorry for that I'm not familiar with iOS development because I'm a Java developer, but I can ask my colleague, who develop iOS apps, for help. Please wait...

**Comment by kula99** [comment]
```
payrequest.merchantCapabilities  = PKMerchantCapability3DS|PKMerchantCapabilityEMV
payment.supportedNetworks = @[PKPaymentNetworkChinaUnionPay];
```

@jlgordo have a try

[Here](http://www.lilongcnc.cc/2016/02/28/9-applepay%E6%94%AF%E4%BB%98%E7%95%8C%E9%9D%A2%E8%B0%83%E7%94%A8%E5%92%8C%E8%8E%B7%E5%8F%96payment%E5%8F%82%E6%95%B0%E9%93%B6%E8%81%94%E6%89%A3%E6%AC%BE%E6%B5%81%E7%A8%8B/) are the issues other developers have met(sorry the article is written in Chinese)
